name: 'Terraform Actions'

on:
  push:
    branches:
      - master
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Format'
        uses: hashicorp/terraform-github-actions@master
        working-directory: './s3'
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
      - name: 'Init'
        uses: hashicorp/terraform-github-actions@master
        working-directory: './s3'
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
      - name: 'Validade'
        uses: hashicorp/terraform-github-actions@master
        working-directory: './s3'
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
      - name: 'Plan'
        uses: hashicorp/terraform-github-actions@master
        working-directory: './s3'
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'