name: 'Terraform Actions'

on:
  push:
    branches:
      - master
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      working-directory: './s3'
      args: '-var-file="validate.tfvars"'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{env.working-directory}}
      - name: 'Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{env.working-directory}}
      - name: 'Validade'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{env.working-directory}}
          args: ${{env.args}}
      - name: 'Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{env.working-directory}}
          args: ${{env.args}}